# Generated by Django 3.2.4 on 2021-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_pics', '0003_pictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/fresh_pics/img/photo_categories', verbose_name='Фото'),
        ),
    ]
